/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type PostSection = {
  _type: 'post.section'
  columns: '1' | '2' | '3'
  blocks?: Array<
    | ({
        _key: string
      } & PostContent)
    | ({
        _key: string
      } & PostMedia)
  >
}

export type PostMedia = {
  _type: 'post.media'
  span?: '1' | '2' | 'full'
  media: BlockMedia
}

export type PostContent = {
  _type: 'post.content'
  span?: '1' | '2' | 'full'
  content: InternationalizedArrayBlockContent
}

export type BlockGallery = {
  _type: 'block.gallery'
  items?: Array<
    | ({
        _key: string
      } & BlockImage)
    | ({
        _key: string
      } & BlockVideo)
  >
}

export type BlockCopy = {
  _type: 'block.copy'
  showHeadline?: boolean
  showText?: boolean
  headline?: InternationalizedArrayText
  text?: InternationalizedArrayText
}

export type ProductSpecs = {
  _type: 'product.specs'
  items?: Array<{
    text: InternationalizedArrayString
    _type: 'spec'
    _key: string
  }>
}

export type BlockSplitMedia = {
  _type: 'block.splitMedia'
  left: BlockMedia
  right: BlockMedia
}

export type BlockMedia = {
  _type: 'block.media'
  type: 'image' | 'video'
  image?: BlockImage
  video?: BlockVideo
}

export type BlockContentSection = {
  _type: 'block.contentSection'
  headline?: InternationalizedArrayText
  text?: InternationalizedArrayText
}

export type BlockVideo = {
  _type: 'block.video'
  muxVideo?: MuxVideo
}

export type BlockText = {
  _type: 'block.text'
  layout?: 'single' | 'twoColumn'
  content?: InternationalizedArrayBlockContent
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockImage = {
  _type: 'block.image'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: InternationalizedArrayString
  credits?: InternationalizedArrayString
}

export type TeamMemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'teamMember'
}

export type Team = {
  _type: 'team'
  heading?: InternationalizedArrayString
  members: Array<
    {
      _key: string
    } & TeamMemberReference
  >
}

export type Stats = {
  _type: 'stats'
  items: Array<{
    value: InternationalizedArrayString
    number: number
    suffix?: InternationalizedArrayString
    label: InternationalizedArrayString
    _key: string
  }>
}

export type Seo = {
  _type: 'seo'
  metaTitle?: InternationalizedArrayString
  metaDescription?: InternationalizedArrayText
  metaImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type MenuItemGroup = {
  _type: 'menuItemGroup'
  title?: InternationalizedArrayString
  items?: Array<
    {
      _key: string
    } & MenuItem
  >
}

export type MenuItem = {
  _type: 'menuItem'
  title: InternationalizedArrayString
  link: Link
}

export type HomeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'home'
}

export type BlogReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'blog'
}

export type ProjectsReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'projects'
}

export type AboutReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'about'
}

export type ContactReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'contact'
}

export type PrivacyPolicyReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'privacyPolicy'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type ProductCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productCategory'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Link = {
  _type: 'link'
  linkType?:
    | 'href'
    | 'page'
    | 'post'
    | 'productCategory'
    | 'product'
    | 'project'
    | 'email'
    | 'phone'
  href?: string
  page?:
    | HomeReference
    | BlogReference
    | ProjectsReference
    | AboutReference
    | ContactReference
    | PrivacyPolicyReference
  post?: PostReference
  productCategory?: ProductCategoryReference
  product?: ProductReference
  project?: ProjectReference
  email?: string
  phone?: string
}

export type Cta = {
  _type: 'cta'
  headline: InternationalizedArrayString
  tagline?: InternationalizedArrayText
  button?: Button
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<
    {
      _key: string
    } & Link
  >
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        {
          _key: string
        } & Link
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: InternationalizedArrayString
  link?: Link
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: InternationalizedArrayText
  name: InternationalizedArrayString
  company?: InternationalizedArrayString
}

export type InternationalizedArrayString = Array<
  {
    _key: string
  } & InternationalizedArrayStringValue
>

export type InternationalizedArrayText = Array<
  {
    _key: string
  } & InternationalizedArrayTextValue
>

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: InternationalizedArrayString
  lastName?: InternationalizedArrayString
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: InternationalizedArrayString
    _type: 'image'
  }
  bio?: InternationalizedArrayText
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Client = {
  _id: string
  _type: 'client'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: InternationalizedArrayString
  darkLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  lightLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  shape?: 'wide' | 'square' | 'tall'
  displaySize?: 'sm' | 'md' | 'lg'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  publishedAt: string
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: InternationalizedArrayString
    _type: 'image'
  }
  body: Array<
    {
      _key: string
    } & PostSection
  >
  slug: Slug
  meta?: {
    title?: InternationalizedArrayString
    description?: InternationalizedArrayText
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type InternationalizedArrayBlockContent = Array<
  {
    _key: string
  } & InternationalizedArrayBlockContentValue
>

export type FormConfigReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'formConfig'
}

export type Contact = {
  _id: string
  _type: 'contact'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  headline?: InternationalizedArrayText
  form: FormConfigReference
  addressTitle?: InternationalizedArrayText
  googleMapsUrl?: string
  mapImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: InternationalizedArrayString
    _type: 'image'
  }
  seo?: Seo
}

export type FormConfig = {
  _id: string
  _type: 'formConfig'
  _createdAt: string
  _updatedAt: string
  _rev: string
  key: 'contact-us'
  description?: InternationalizedArrayText
  recipients: Array<string>
  hubspotFormId?: string
  successMessage?: InternationalizedArrayText
  errorText?: InternationalizedArrayText
  consentText?: InternationalizedArrayText
  notificationsLabel?: InternationalizedArrayString
  personalDataNote?: InternationalizedArrayText
  notificationsSubscriptionTypeId?: number
  privacyPage?: PrivacyPolicyReference
}

export type PrivacyPolicy = {
  _id: string
  _type: 'privacyPolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  body?: InternationalizedArrayBlockContent
  seo?: Seo
}

export type About = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  headline?: InternationalizedArrayText
  pageBuilder?: Array<
    | ({
        _key: string
      } & BlockText)
    | ({
        _key: string
      } & BlockMedia)
    | ({
        _key: string
      } & BlockContentSection)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Cta)
  >
  seo?: Seo
}

export type Projects = {
  _id: string
  _type: 'projects'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  seo?: Seo
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  blogPostFooter?: InternationalizedArrayBlockContent
  seo?: Seo
}

export type ClientReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'client'
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: {
    columns: Array<{
      items: Array<
        | ({
            _key: string
          } & BlockMedia)
        | ({
            _key: string
          } & BlockText)
      >
      _type: 'heroColumn'
      _key: string
    }>
  }
  featuredProducts?: {
    headline?: InternationalizedArrayString
    description?: InternationalizedArrayText
    categories?: Array<
      {
        _key: string
      } & ProductCategoryReference
    >
  }
  clients?: Array<
    {
      _key: string
    } & ClientReference
  >
  featuredProject?: ProjectReference
  featuredPosts?: Array<
    {
      _key: string
    } & PostReference
  >
  seo?: Seo
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayText
  description: InternationalizedArrayBlockContentTextOnly
  excerpt?: InternationalizedArrayText
  blocks?: Array<
    | ({
        _key: string
      } & BlockCopy)
    | ({
        _key: string
      } & BlockMedia)
  >
  output?: Array<
    {
      _key: string
    } & BlockImage
  >
  mainImage?: BlockImage
  heroVideo?: MuxVideo
  gallery?: Array<
    {
      _key: string
    } & BlockImage
  >
  product?: ProductReference
  slug: Slug
  legacySlugs?: Array<string>
  seo?: Seo
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  category: ProductCategoryReference
  excerpt?: InternationalizedArrayText
  description: InternationalizedArrayBlockContentTextOnly
  specs?: ProductSpecs
  copy?: BlockCopy
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  slug: Slug
  mainImage: BlockImage
  heroVideo?: MuxVideo
  seo?: Seo
}

export type MuxVideoAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'mux.videoAsset'
}

export type MuxVideo = {
  _type: 'mux.video'
  asset?: MuxVideoAssetReference
}

export type InternationalizedArrayBlockContentTextOnly = Array<
  {
    _key: string
  } & InternationalizedArrayBlockContentTextOnlyValue
>

export type ProductCategory = {
  _id: string
  _type: 'productCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  description: InternationalizedArrayBlockContentTextOnly
  excerpt?: InternationalizedArrayText
  slug: Slug
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  mainImage: BlockImage
  heroVideo?: MuxVideo
  seo?: Seo
}

export type MenuReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'menu'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  description?: InternationalizedArrayText
  siteMenu?: MenuReference
  footerMenu?: Array<
    {
      _key: string
    } & MenuItem
  >
  getInTouchCTA?: {
    heading?: InternationalizedArrayString
    buttonLabel?: InternationalizedArrayString
    link?: Link
  }
  locations?: Array<{
    name?: InternationalizedArrayString
    content?: InternationalizedArrayBlockContentTextOnly
    _key: string
  }>
  socialLinks?: Array<{
    platform: 'facebook' | 'instagram' | 'x' | 'linkedin' | 'youtube' | 'tiktok' | 'threads'
    label?: InternationalizedArrayString
    link?: string
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: InternationalizedArrayString
    metadataBase?: string
    _type: 'image'
  }
}

export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  items?: Array<
    | ({
        _key: string
      } & MenuItemGroup)
    | ({
        _key: string
      } & MenuItem)
  >
  ctaLabel?: InternationalizedArrayString
}

export type MuxVideoAsset = {
  _id: string
  _type: 'mux.videoAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: string
  assetId?: string
  playbackId?: string
  filename?: string
  thumbTime?: number
  data?: MuxAssetData
}

export type MuxAssetData = {
  _type: 'mux.assetData'
  resolution_tier?: string
  upload_id?: string
  created_at?: string
  id?: string
  status?: string
  max_stored_resolution?: string
  passthrough?: string
  encoding_tier?: string
  video_quality?: string
  master_access?: string
  aspect_ratio?: string
  duration?: number
  max_stored_frame_rate?: number
  mp4_support?: string
  max_resolution_tier?: string
  tracks?: Array<
    {
      _key: string
    } & MuxTrack
  >
  playback_ids?: Array<
    {
      _key: string
    } & MuxPlaybackId
  >
  static_renditions?: MuxStaticRenditions
  master?: MuxMasterFile
}

export type MuxMasterFile = {
  _type: 'mux.masterFile'
  status?: string
  url?: string
}

export type MuxStaticRenditions = {
  _type: 'mux.staticRenditions'
  status?: string
  files?: Array<
    {
      _key: string
    } & MuxStaticRenditionFile
  >
}

export type MuxStaticRenditionFile = {
  _type: 'mux.staticRenditionFile'
  name?: string
  ext?: string
  height?: number
  width?: number
  bitrate?: number
  filesize?: string
  type?: string
  status?: string
  resolution_tier?: string
  resolution?: string
  id?: string
  passthrough?: string
}

export type MuxPlaybackId = {
  _type: 'mux.playbackId'
  id?: string
  policy?: string
}

export type MuxTrack = {
  _type: 'mux.track'
  id?: string
  type?: string
  max_width?: number
  max_frame_rate?: number
  duration?: number
  max_height?: number
  language_code?: string
  name?: string
  status?: string
  text_source?: string
  text_type?: string
}

export type InternationalizedArrayBlockContentTextOnlyValue = {
  _type: 'internationalizedArrayBlockContentTextOnlyValue'
  value?: BlockContentTextOnly
  language: string
}

export type InternationalizedArrayBlockContentValue = {
  _type: 'internationalizedArrayBlockContentValue'
  value?: BlockContent
  language: string
}

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue'
  value?: string
  language: string
}

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue'
  value?: string
  language: string
}

export type MediaFolderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'media.folder'
}

export type MediaFolder = {
  _id: string
  _type: 'media.folder'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  parent?: MediaFolderReference
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PostSection
  | PostMedia
  | PostContent
  | BlockGallery
  | BlockCopy
  | ProductSpecs
  | BlockSplitMedia
  | BlockMedia
  | BlockContentSection
  | BlockVideo
  | BlockText
  | SanityImageAssetReference
  | BlockImage
  | TeamMemberReference
  | Team
  | Stats
  | Seo
  | MenuItemGroup
  | MenuItem
  | HomeReference
  | BlogReference
  | ProjectsReference
  | AboutReference
  | ContactReference
  | PrivacyPolicyReference
  | PostReference
  | ProductCategoryReference
  | ProductReference
  | ProjectReference
  | Link
  | Cta
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Testimonial
  | InternationalizedArrayString
  | InternationalizedArrayText
  | TeamMember
  | SanityImageCrop
  | SanityImageHotspot
  | Client
  | Post
  | Slug
  | InternationalizedArrayBlockContent
  | FormConfigReference
  | Contact
  | FormConfig
  | PrivacyPolicy
  | About
  | Projects
  | Blog
  | ClientReference
  | Home
  | Project
  | Product
  | MuxVideoAssetReference
  | MuxVideo
  | InternationalizedArrayBlockContentTextOnly
  | ProductCategory
  | MenuReference
  | Settings
  | Menu
  | MuxVideoAsset
  | MuxAssetData
  | MuxMasterFile
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | InternationalizedArrayBlockContentTextOnlyValue
  | InternationalizedArrayBlockContentValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
